{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "springress.fullname" . }}-controller
  labels:
    app: {{ template "springress.name" . }}
    chart: {{ template "springress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get","list","read","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "springress.fullname" . }}-controller
  labels:
    app: {{ template "springress.name" . }}
    chart: {{ template "springress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "springress.fullname" . }}-controller
subjects:
  - name: {{ template "springress.serviceAccountName" . }}-controller
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "springress.fullname" . }}-controller
  labels:
    app: {{ template "springress.name" . }}
    chart: {{ template "springress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "springress.fullname" . }}-controller
  labels:
    app: {{ template "springress.name" . }}
    chart: {{ template "springress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "springress.fullname" . }}-controller
subjects:
  - name: {{ template "springress.serviceAccountName" . }}-controller
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
{{- end }}
